name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "22.18.0"
    - run: npm install
    - run: npm add-use-client
    - run: npm run lint
    - run: npm run build
